language: cpp

compiler:
  - clang
  - gcc
  
env:
  global:
    - secure: "QW5QTwmLqovoDDrwVGXIOh+jd+ArwWSAy2P1U5xDW3C7oE5lgHQH3bqStEv63aOxvpN9cgqjroXQfCpKz+nNO7Rur0MY7UXCUxk0VizCOn4CUg7K7XeHTJEvzGRke2j7QUNigE5GTu9ABAeSN/AfHAtWVCFrecMINqTLWWC3pB/dTalCX6NoQb2f1z2nbdHa+suT8NoUo14eXrQfIZ9xnVrQ7NYuMXyb5A0akyQSq1oNb+5yj1o1wdmaNaCkalGyN2Oj/aD8urSU65sahwOQlhCwnxKDVuFqhcgV4ux6k42B7VJuVhxC2j71vCS4Kfka00/WVTNJXmdDxB873o+GqGVElvc5QeimQX34Zw2b+u77teZku4y33wm1wazh6mGh13/4EzA325rqjaxlge4EE5Bzq5qIhmaLspwob1EQD/waEhSDptNCK5bgP+OBtGi1f8vAnjlhh/3U10oWtAV1faV88zx9q0mWb4yYyoLP6D3ViglL62E9hKpwL2uXpGeb6yTCHfcpNMqkwFwYFt+Dj5vJ9RG4kmlsg4oXUn47zCOwj2ynOR24q9xgR+7d2Zj2vzfE/PPWbn8UGO6VcZtn6CpBUn6kMpfh5BcvBA06aFh/neW9WxAe9W7X6w1n1whpkTE2ro3iJDlVDiY+QTlCuZJg6EvLmKuHMf6oKM5WNC0="
  matrix:
    - QT_BASE=52
    - QT_BASE=53
    - QT_BASE=54
    - QT_BASE=55

before_install:
  - if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$QT_BASE" = "52" ]; then sudo add-apt-repository ppa:beineri/opt-qt521 -y; fi
  - if [ "$QT_BASE" = "53" ]; then sudo add-apt-repository ppa:beineri/opt-qt532 -y; fi
  - if [ "$QT_BASE" = "54" ]; then sudo add-apt-repository ppa:beineri/opt-qt542 -y; fi
  - if [ "$QT_BASE" = "55" ]; then sudo add-apt-repository ppa:beineri/opt-qt551 -y; fi
  - sudo apt-add-repository -y ppa:libreoffice/libreoffice-4-2 # used to install an up-to-date doxygen
  - sudo apt-get update -qq

install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq gcc-4.8 g++-4.8; export CXX="g++-4.8" CC="gcc-4.8"; $CXX --version; fi
  - if [ "$QT_BASE" = "52" ]; then sudo apt-get install -qq qt52base qt52tools qt52webkit-examples libxslt-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev; source /opt/qt52/bin/qt52-env.sh; fi
  - if [ "$QT_BASE" = "53" ]; then sudo apt-get install -qq qt53base qt53tools qt53webkit-examples; source /opt/qt53/bin/qt53-env.sh; fi
  - if [ "$QT_BASE" = "54" ]; then sudo apt-get install -qq qt54base qt54tools qt54webkit-examples; source /opt/qt54/bin/qt54-env.sh; fi
  - if [ "$QT_BASE" = "55" ]; then sudo apt-get install -qq qt55base qt55tools qt55webkit-examples; source /opt/qt55/bin/qt55-env.sh; fi
  - sudo apt-get install -qq libglu1-mesa-dev doxygen graphviz

script:
  - mkdir build
  - cd build
  - qmake ../librepcb.pro -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC"
  - make -j 8
  - ./generated/unix/tests # run all unit tests
  - cd ../

# run doxygen and upload the html output to github (gh-pages of LibrePCB-Doxygen)
after_success:
  - ./dev/doxygen/travis_build_doxygen.sh
