language: cpp
sudo: required
cache: ccache
notifications:
  email:
    on_success: change
    on_failure: change

matrix:
  fast_finish: true
  include:
    # Ubuntu 14.04 + GCC 4.8 + Qt 5.2 + Doxygen Generation (all packages from official Ubuntu repositories)
    - os: linux
      dist: trusty
      compiler: gcc
      env: BUILD_DOXYGEN=true DEPLOY_APPIMAGE=false QT_BASE="trusty"
    # Ubuntu 14.04 + Clang + Qt from PPA (https://launchpad.net/~beineri) + AppImage deployment
    - os: linux
      dist: trusty
      compiler: clang
      env: BUILD_DOXYGEN=false DEPLOY_APPIMAGE=true QT_BASE="qt58" QT_PPA="ppa:beineri/opt-qt58-trusty"
    # OS X + GCC
    - os: osx
      compiler: gcc
      env: BUILD_DOXYGEN=false
    # OS X + Clang
    - os: osx
      compiler: clang
      env: BUILD_DOXYGEN=false

install:
  - source ./dev/travis/install.sh # source required because it modifies the environment

script:
  - ./dev/travis/build.sh
  - ./dev/travis/run_tests.sh
  - ./dev/travis/update_doxygen.sh
  - ./dev/travis/build_appimage.sh

