language: cpp
sudo: required
cache: ccache
notifications:
  email:
    on_success: change
    on_failure: change

matrix:
  fast_finish: true
  include:
    # Ubuntu 14.04 + GCC 4.8 + Qt 5.2 + Doxygen Generation (all packages from official Ubuntu repositories)
    - os: linux
      dist: trusty
      compiler: gcc
      env: BUILD_DOXYGEN=true DEPLOY_APPIMAGE=false DEPLOY_INSTALLER=false QT_BASE="trusty"
    # Ubuntu 14.04 + Clang + Qt from PPA (https://launchpad.net/~beineri) + AppImage deployment
    - os: linux
      dist: trusty
      compiler: clang
      env: BUILD_DOXYGEN=false DEPLOY_APPIMAGE=true DEPLOY_INSTALLER=true TX_UPLOAD=true QT_BASE="qt59" QT_PPA="ppa:beineri/opt-qt591-trusty"
    # OS X + GCC
    - os: osx
      compiler: gcc
      env: BUILD_DOXYGEN=false DEPLOY_BUNDLE=false DEPLOY_INSTALLER=false
    # OS X + Clang
    - os: osx
      compiler: clang
      env: BUILD_DOXYGEN=false DEPLOY_BUNDLE=true DEPLOY_INSTALLER=true

install:
  - source ./ci/install_dependencies.sh # source required because it modifies the environment

script:
  - ./ci/build.sh                 || travis_terminate 1
  - ./ci/test.sh                  || travis_terminate 1
  - ./ci/upload_artifacts.sh      || travis_terminate 1
